# See https://github.com/golangci/golangci-lint/issues/2649 for which linters
# are supported.
run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - ireturn # This library intentionally return interfaces.
    - wrapcheck # This library structures are intended to store errors.

    # To Be Enabled
    - varnamelen
    - containedctx

    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - varcheck

    # disabled because of generics
    # See: https://github.com/golangci/golangci-lint/issues/2649
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sagmor/fun)
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: banned-characters
        arguments: ["Ω", "Σ", "σ", "7"]
      - name: cognitive-complexity
        arguments: [7]
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: argument-limit
        arguments: [5]
      - name: max-public-structs
        arguments: [3]
      - name: function-result-limit
        arguments: [2]
      # Disabled:
      - name: file-header
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: confusing-naming
        disabled: true # Has issues with generics
      - name: line-length-limit
        disabled: true # Using lll instead of revive for this
      - name: function-length
        disabled: true

issues:
  exclude-use-default: false

  exclude-rules:
    - path: "_test\\.go"
      linters:
        - revive
      text: add-constant
