name: Build
on: 
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request: {}
  schedule:
    - cron: "0 2 * * 1"
permissions:
  contents: read
jobs:
  build:
    name: Build
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        go-version:
          - "1.18.5"
          - "1.19"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./tests/... -covermode=atomic -coverpkg ./... -coverprofile=coverage.out
      - name: Convert coverage data to lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Publish coverage data
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.github_token }}
