name: build
on: 
  push:
    branches: 
    - main
  pull_request: {}
  schedule:
  - cron: "0 2 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        go_version: ["1.18.5", "1.19"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
