name: Build
on: 
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request: {}
  schedule:
    - cron: "0 2 * * 1"
permissions:
  contents: read
jobs:
  build:
    name: Build
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        go_version:
          - "1.18.5"
          - "1.19"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./tests/...
